blank_issues_enabled: false
contact_links:
- name: Get help from the Home Assistant community
  url: https://community.home-assistant.io/t/qolsys-iq-panel-2-and-3rd-party-integration/231405
  about: |
    There is a live thread on the Home Assistant community forums where you can get help from
    many users of this integration
